name: Unit and integration tests

on: [workflow_dispatch, pull_request]

jobs:
  check:
    name: Run tests
    runs-on: ubuntu-latest
    concurrency:
      group: apps-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Unit tests
        run: yarn test
